= Yatc - Yet Another Tcl Clone

** THIS SOFTWARE IS EXPERIMENTAL AND ISN'T PROBABLY READY FOR PRODUCTION USE **

**Yatc** is a relatively tiny and ultra-portable virtual machine for running scripts written in Yatc - a scripting language heavily mocking Tcl and Ruby. The main goals of this project are:

[squares]
- to create an extendable scripting language that would allow writing extensions for embedded systems
- to make a virtual machine for that language that can be really easily embedded into a commercial product without any licensing problems
- to make that virtual machine as portable as possible

== Building

You'll need:
- macOS, Linux or FreeBSD 
- GCC or clang
- A full installation of KDE Plasma 4 or 5 if you want the KDE frontend

Run this command to build:

[source,bash]
----
$ sh build.sh
----

This will produce ``yatc`` - the standalone intepreter - and ``libyatc.a`` - the static library containing the embeddable version of the interpreter.

== Docs

See the wiki for this project, I guess?

== License

[source]
----
BSD 3-Clause License

Copyright (c) 2019, Tim K/RoverAMD <timprogrammer@rambler.ru>
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
----
